In [1]:
import pandas as pd
import numpy as np

In [2]:
# read the data
d=pd.read_table(r'C:\Users\Tanvir Khan\Desktop\fruit.txt')
d.head()

fruit_label fruit_name fruit_subtype   mass  width  height  color_score
0            1      apple  granny_smith  192.0    8.4     7.3         0.55
1            1      apple  granny_smith  180.0    8.0     6.8         0.59
2            1      apple  granny_smith  176.0    7.4     7.2         0.60
3            2   mandarin      mandarin   86.0    6.2     4.7         0.80
4            2   mandarin      mandarin   84.0    6.0     4.6         0.79

In [3]:
# crosstab
pd.crosstab(index=d['fruit_label'], columns='count')

col_0        count
fruit_label       
1               19
2                5
3               19
4               16

In [4]:
# recode values to make the column binary
d['Lab']=d['fruit_label'].replace({1:'Apple', 2:'Not_Apple', 3:'Not_Apple', 4:'Not_Apple' })
d.head()

fruit_label fruit_name fruit_subtype   mass  width  height  color_score  \
0            1      apple  granny_smith  192.0    8.4     7.3         0.55   
1            1      apple  granny_smith  180.0    8.0     6.8         0.59   
2            1      apple  granny_smith  176.0    7.4     7.2         0.60   
3            2   mandarin      mandarin   86.0    6.2     4.7         0.80   
4            2   mandarin      mandarin   84.0    6.0     4.6         0.79   

         Lab  
0      Apple  
1      Apple  
2      Apple  
3  Not_Apple  
4  Not_Apple

In [5]:
# may recode in this way too
d=pd.read_table(r'C:\Users\Tanvir Khan\Desktop\fruit.txt')
d.head()
d.loc[d['fruit_name']!='apple', 'Lab']=0 #fruit lab is the new column name
d.loc[d['fruit_name']=='apple', 'Lab']=1
d.head()

fruit_label fruit_name fruit_subtype   mass  width  height  color_score  \
0            1      apple  granny_smith  192.0    8.4     7.3         0.55   
1            1      apple  granny_smith  180.0    8.0     6.8         0.59   
2            1      apple  granny_smith  176.0    7.4     7.2         0.60   
3            2   mandarin      mandarin   86.0    6.2     4.7         0.80   
4            2   mandarin      mandarin   84.0    6.0     4.6         0.79   

   Lab  
0  1.0  
1  1.0  
2  1.0  
3  0.0  
4  0.0

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X=d[['height', 'width']]
y=d[['Lab']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=.25)

In [7]:
y_train.head()

Lab
42  0.0
48  0.0
7   0.0
14  1.0
32  0.0

In [20]:
lg=LogisticRegression(C=1e9) #https://stackoverflow.com/questions/22851316/what-is-the-inverse-of-regularization-strength-in-logistic-regression-how-shoul
# for more details see ridge regression regularization

lg.fit(X_train,y_train)

lg.score(X_train, y_train)

lg.score(X_test, y_test)

0.6666666666666666

In [9]:
lg.predict(X_test)
lg.predict(X_train)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
from sklearn.metrics import confusion_matrix

y_pred=lg.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[11,  0],
       [ 4,  0]], dtype=int64)

In [11]:
# {:.2f} ask to print the number upto 2 decimal
print('The Accuracy in Train Set is: {:.3f}'.format(lg.score(X_test, y_test)))

The Accuracy in Train Set is: 0.733


In [22]:
# get the coefficient
print(lg.coef_)
lg.intercept_

[[-0.17269886  1.22499662]]


array([-8.16998142])

In [13]:
# for getting the summary table
d.head()
d.loc[d['fruit_name']!='apple', 'Lab1']=0
d.loc[d['fruit_name']=='apple', 'Lab1']=1
d.head()

fruit_label fruit_name fruit_subtype   mass  width  height  color_score  \
0            1      apple  granny_smith  192.0    8.4     7.3         0.55   
1            1      apple  granny_smith  180.0    8.0     6.8         0.59   
2            1      apple  granny_smith  176.0    7.4     7.2         0.60   
3            2   mandarin      mandarin   86.0    6.2     4.7         0.80   
4            2   mandarin      mandarin   84.0    6.0     4.6         0.79   

   Lab  Lab1  
0  1.0   1.0  
1  1.0   1.0  
2  1.0   1.0  
3  0.0   0.0  
4  0.0   0.0

In [23]:
X=d[['height','width']]
y=d['Lab'].astype('category')

X_train, X_test, y_train, y_test=train_test_split(X, y, random_state=0, test_size=.25)

In [25]:
# if we want the summary table 
import statsmodels.api as sm
XC=sm.add_constant(X_train, prepend=True)

lg=sm.Logit(y_train, XC)
lgmd=lg.fit()
print(lgmd.summary2())

# odds ratio
print(np.exp(lgmd.params))

Optimization terminated successfully.
         Current function value: 0.552831
         Iterations 6
                        Results: Logit
Model:              Logit            No. Iterations:   6.0000 
Dependent Variable: Lab              Pseudo R-squared: 0.138  
Date:               2018-04-27 08:49 AIC:              54.6491
No. Observations:   44               BIC:              60.0017
Df Model:           2                Log-Likelihood:   -24.325
Df Residuals:       41               LL-Null:          -28.232
Converged:          1.0000           Scale:            1.0000 
---------------------------------------------------------------
           Coef.   Std.Err.     z     P>|z|    [0.025    0.975]
---------------------------------------------------------------
const     -8.1701    3.7418  -2.1835  0.0290  -15.5040  -0.8363
height    -0.1727    0.2339  -0.7385  0.4602   -0.6311   0.2857
width      1.2250    0.5071   2.4159  0.0157    0.2312   2.2189

const     0.000283
height    0.84

In [16]:
# odds ratio interp
# the constant, if both height and weight are 0, the odds of the obhect being an apple is .000283
# for one unit increase in height we expect a decrease in .08413-1 increase (decrease if negative) in the odds
## being an apple
# same for widhth

In [17]:
y_train.head()

42    0.0
48    0.0
7     0.0
14    1.0
32    0.0
Name: Lab, dtype: category
Categories (2, float64): [0.0, 1.0]

In [18]:
## interpretation of logistic regression
# logit(p)=log(p/(p-1))=b0+b1*x
# https://drive.google.com/drive/u/0/folders/0B1kh19zHHm3CZzJsdzVsMTkxOGM